# Project: PDG-Debugger
# Makefile created by Embarcadero Dev-C++ 6.0

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = PDG-Debugger_private.res
OBJ      = main.o $(RES)
LINKOBJ  = main.o $(RES)
LIBS     = -L"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/lib" -L"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/x86_64-w64-mingw32/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/x86_64-w64-mingw32/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/D/downloads/CodeBlocks/share/CodeBlocks/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = PDG-Debugger.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
DEL      = del /f /q

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${DEL} $(OBJ) $(BIN) 2>nul

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

PDG-Debugger_private.res: PDG-Debugger_private.rc 
	$(WINDRES) -i PDG-Debugger_private.rc --input-format=rc -o PDG-Debugger_private.res -O coff 

